# SPDX-FileCopyrightText: Copyright (c) 2024 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.

[package]
title = "CGP Validator Extension"
version = "0.1.0"  # Semantic Versioning is used: https://semver.org/
description = "Spacedata CG Pipeline Validator Extension"
category = "Validator"  # How to categorize this in the Extension Manager
changelog = "docs/CHANGELOG.md"
icon = "data/icon.png"  # Icon to show in the Extension Manager
keywords = ["kit", "example", "extension"]  # Search keywords for the Extension Manager
preview_image = "data/preview.png"  # Preview to show in the Extension Manager
readme  = "docs/README.md"  # Path (relative to the root) or content of readme markdown file for UI
repository = ""  # URL of the extension source repository


[dependencies]


[settings]


[documentation]
pages = [
    "docs/Overview.md",
    "docs/CHANGELOG.md",
]


[[test]]
dependencies = [
]

args = [
]

[[native.library]]
"filter:platform"."linux-x86_64"."path" = "lib/${lib_prefix}cgpValidatorPlugin${lib_ext}"
"filter:platform"."windows-x86_64"."path" = "lib/${lib_prefix}cgpValidatorPlugin${lib_ext}"

[[python.module]]
name = "spacedata.cgp_validator_extension"

[dependencies]
"omni.usd.libs" = {}